lzw:
	g++ -o lzw -Werror -std=c++17 lzw.cpp
	g++ -o uncompress -Werror -std=c++17 uncompress.cpp

clean:
	if [ -f lzw ]; \
	then \
		rm lzw; \
	fi
	if [ -f uncompress ]; \
	then \
		rm uncompress; \
	fi
